"""Ren'Py reinjection: generate standard Ren'Py translation files.

Uses Ren'Py string-translation mechanism (``translate <lang> strings:``
old/new pairs), which matches translations by *original text* and therefore
works without Ren'Py engine-assigned translation-unit identifiers — this
is the approach Ren'Py itself documents for translations produced outside
the launcher. The original game is never modified: output is a patch
directory mirroring the game layout under ``game/tl/<target_lang>/``.

All currently-extracted kinds become string pairs:

* ``say`` / narrator lines  -> old/new (Ren'Py applies string translation
  to displayed dialogue text)
* ``menu`` choices          -> old/new
* ``translate strings``     -> old/new (re-emitted, carrying existing
  translations through)
"""

from __future__ import annotations

from pathlib import Path

from almurrib.core.errors import ExportError
from almurrib.core.model import LocalizationEntry


def _quote(text: str) -> str:
    """Quote a string for Ren'Py (double-quoted, escaped)."""
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def generate_translation_files(
    entries: list[LocalizationEntry],
    *,
    target_lang: str,
) -> dict[str, str]:
    """Build ``{relative_path: file_content}`` for all translatable entries.

    Only entries with a translation are emitted; flagged entries are still
    emitted (with their flags as comments) so a human can review in place.
    Untranslated entries are skipped (Ren'Py falls back to source text).
    """
    translated = [e for e in entries if e.translated_text]
    if not translated:
        return {}

    # Deterministic order: source file, then line.
    def key(e: LocalizationEntry) -> tuple[str, int]:
        ref = e.source_refs[0] if e.source_refs else None
        return (ref.file if ref else "", ref.line if ref else 0)

    lines = [
        "# Generated by almurrib — Arabic localization patch.",
        "# Uses string translation so it loads without engine-generated ids.",
        "",
        f"translate {target_lang} strings:",
        "",
    ]
    for entry in sorted(translated, key=key):
        ref = entry.source_refs[0] if entry.source_refs else None
        where = f"{ref.file}:{ref.line}" if ref else "?"
        speaker = f" [{entry.speaker}]" if entry.speaker else ""
        lines.append(f"    # {where}{speaker}")
        lines.append(f"    old {_quote(entry.source_text)}")
        new_line = f"    new {_quote(entry.translated_text or '')}"
        if entry.qa_flags:
            new_line += "  # QA: " + "; ".join(entry.qa_flags)
        lines.append(new_line)
        lines.append("")

    return {f"game/tl/{target_lang}/strings.rpy": "\n".join(lines)}


def write_translation_patch(
    entries: list[LocalizationEntry],
    *,
    target_lang: str,
    output_dir: Path,
) -> list[Path]:
    """Write the generated translation files into ``output_dir``.

    The output directory mirrors the game layout; it never touches the
    original game. Returns the list of written paths.
    """
    files = generate_translation_files(entries, target_lang=target_lang)
    if not files:
        raise ExportError(
            "no translated entries to export",
            hint="run translation first, or check that entries have translated_text.",
        )
    written: list[Path] = []
    for rel, content in files.items():
        target = output_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written
