"""Ren'Py reinjection: generate standard Ren'Py translation files.

Uses Ren'Py string-translation mechanism (``translate <lang> strings:``
old/new pairs), which matches translations by *original text* and therefore
works without Ren'Py engine-assigned translation-unit identifiers — this
is the approach Ren'Py itself documents for translations produced outside
the launcher. The original game is never modified: output is a patch
directory mirroring the game layout under ``game/tl/<target_lang>/``.

All currently-extracted kinds become string pairs:

* ``say`` / narrator lines  -> old/new (Ren'Py applies string translation
  to displayed dialogue text)
* ``menu`` choices          -> old/new
* ``translate strings``     -> old/new (re-emitted, carrying existing
  translations through)
"""

from __future__ import annotations

import re
from pathlib import Path

from almurrib.core.errors import ExportError
from almurrib.core.model import LocalizationEntry


def _quote(text: str) -> str:
    """Quote a string for Ren'Py (double-quoted, escaped)."""
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


# Safe Ren'Py language identifiers: used as a directory name AND a
# `translate <lang> strings:` header. Anything else risks path traversal
# or a broken translation file.
_VALID_LANG_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,31}$")


def validate_target_lang(target_lang: str) -> str:
    """Reject unsafe language identifiers (traversal, separators, empty)."""
    if not _VALID_LANG_RE.match(target_lang or ""):
        raise ExportError(
            f"unsafe target language identifier: {target_lang!r}",
            hint="use a short identifier like 'ar', 'arabic', 'fr', 'de'.",
        )
    return target_lang


def generate_translation_files(
    entries: list[LocalizationEntry],
    *,
    target_lang: str,
) -> dict[str, str]:
    """Build ``{relative_path: file_content}`` for all translatable entries.

    Only entries with a translation are emitted; flagged entries are still
    emitted (with their flags as comments) so a human can review in place.
    Untranslated entries are skipped (Ren'Py falls back to source text).

    Deduplication rule: identical (source_text, translated_text) pairs are
    emitted ONCE with every location listed (Ren'Py string translation
    matches by source text, so duplicates would be dead weight). The same
    source with DIFFERING translations is emitted per entry with a NOTE —
    collapsing those would silently pick a winner.
    """
    validate_target_lang(target_lang)
    translated = [e for e in entries if e.translated_text]
    if not translated:
        return {}

    # Deterministic order: source file, then line.
    def key(e: LocalizationEntry) -> tuple[str, int]:
        ref = e.source_refs[0] if e.source_refs else None
        return (ref.file if ref else "", ref.line if ref else 0)

    ordered = sorted(translated, key=key)
    # Group identical pairs; keep first-seen order of groups.
    groups: dict[tuple[str, str], list[LocalizationEntry]] = {}
    for entry in ordered:
        groups.setdefault(
            (entry.source_text, entry.translated_text or ""), []
        ).append(entry)
    # Same source, differing translations: warn instead of collapsing.
    by_source: dict[str, set[str]] = {}
    for (source, new) in groups:
        by_source.setdefault(source, set()).add(new)

    lines = [
        "# Generated by almurrib — Arabic localization patch.",
        "# Uses string translation so it loads without engine-generated ids.",
        "",
        f"translate {target_lang} strings:",
        "",
    ]
    for (source, new), members in groups.items():
        locations = []
        for member in members:
            ref = member.source_refs[0] if member.source_refs else None
            where = f"{ref.file}:{ref.line}" if ref else "?"
            speaker = f" [{member.speaker}]" if member.speaker else ""
            locations.append(f"{where}{speaker}")
        lines.append(f"    # {'; '.join(locations)}")
        if len(by_source[source]) > 1:
            lines.append(
                "    # NOTE: same source has differing translations; "
                "review which one Ren'Py should use."
            )
        lines.append(f"    old {_quote(source)}")
        new_line = f"    new {_quote(new)}"
        qa = sorted({flag for m in members for flag in m.qa_flags})
        if qa:
            new_line += "  # QA: " + "; ".join(qa)
        lines.append(new_line)
        lines.append("")

    return {f"game/tl/{target_lang}/strings.rpy": "\n".join(lines)}


def write_translation_patch(
    entries: list[LocalizationEntry],
    *,
    target_lang: str,
    output_dir: Path,
) -> list[Path]:
    """Write the generated translation files into ``output_dir``.

    The output directory mirrors the game layout; it never touches the
    original game. Returns the list of written paths.
    """
    files = generate_translation_files(entries, target_lang=target_lang)
    if not files:
        raise ExportError(
            "no translated entries to export",
            hint="run translation first, or check that entries have translated_text.",
        )
    written: list[Path] = []
    for rel, content in files.items():
        target = output_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written
