"""TEST HARNESS ONLY - not a production engine adapter.

Converts the browser game's dialogue.json into a Ren'Py-style project
(rpy/game/script.rpy) that the CURRENT Almurrib pipeline can extract.
Single source of truth stays dialogue.json; the .rpy is derived and
regenerable. Speaker display names are plain (glossary covers names here).

Usage:
    python tools/json_to_rpy.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "game_data" / "dialogue.json"
OUT_DIR = ROOT / "rpy" / "game"


def _rpy_string(text: str) -> str:
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    speakers: dict[str, str] = {}
    for node in data["nodes"]:
        if node.get("speaker"):
            speakers.setdefault(node["speaker"], f"c{len(speakers)}")
    lines = ["# GENERATED by tools/json_to_rpy.py - do not hand-edit.",
             "# Source of truth: game_data/dialogue.json", ""]
    for name, var in sorted(speakers.items(), key=lambda kv: kv[1]):
        lines.append(f'define {var} = Character("{name}")')
    lines += ["", "label start:", "    jump node_dlg_001", ""]
    for node in data["nodes"]:
        lines.append(f"label node_{node['id']}:")
        var = speakers.get(node["speaker"] or "")
        prefix = f"{var} " if var else ""
        lines.append(f"    {prefix}{_rpy_string(node['text'])}")
        for choice in node.get("choices", []):
            lines.append("    menu:")
            lines.append(f"        {_rpy_string(choice['text'])}:")
            for flag in sorted((choice.get("set") or {})):
                lines.append(f"            $ flags_{flag} = True")
            lines.append(f"            jump node_{choice['next']}")
        if node.get("next"):
            lines.append(f"    jump node_{node['next']}")
        elif not node.get("choices"):
            lines.append("    return")
        lines.append("")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "script.rpy").write_text("\n".join(lines), encoding="utf-8")
    count = len(data["nodes"]) + sum(len(n.get("choices", [])) for n in data["nodes"])
    print(f"wrote {OUT_DIR / 'script.rpy'} ({count} strings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
