# Generated by almurrib — Arabic localization patch.
# Uses string translation so it loads without engine-generated ids.

translate ar strings:

    # game/script.rpy:13 [Sylvie]
    old "Good evening. I thought you were going to be late."
    new "<ar>Good evening. I thought you were going to be late.</ar>"  # QA: no_arabic_script:<ar>Good evening. I thought you were going to be late.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Good; suspicious_latin:evening; suspicious_latin:thought; suspicious_latin:were; suspicious_latin:you

    # game/script.rpy:17 [Sylvie]
    old "Welcome to Station 7, {player_name}! Night shift starts in seven minutes."
    new "<ar>Welcome to Station 7, {player_name}! Night shift starts in seven minutes.</ar>"  # QA: no_arabic_script:<ar>Welcome to Station 7, {player_name}! Night shift starts in seven minutes.</a; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Night; suspicious_latin:Station; suspicious_latin:Welcome; suspicious_latin:shift; suspicious_latin:to

    # game/script.rpy:21 [Mira]
    old "Great. Another interview at midnight. This station protocol makes no sense."
    new "<ar>Great. Another interview at midnight. This station protocol makes no sense.</ar>"  # QA: no_arabic_script:<ar>Great. Another interview at midnight. This station protocol makes no sense.<; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Another; suspicious_latin:Great; suspicious_latin:at; suspicious_latin:interview; suspicious_latin:midnight

    # game/script.rpy:25 [Captain Rowan]
    old "Quiet, Mira. {player_name}, I am Captain Rowan. Walk with me to the control room."
    new "<ar>Quiet, Mira. {player_name}, I am Captain Rowan. Walk with me to the control room.</ar>"  # QA: no_arabic_script:<ar>Quiet, Mira. {player_name}, I am Captain Rowan. Walk with me to the control ; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Captain; suspicious_latin:Mira; suspicious_latin:Quiet; suspicious_latin:Rowan; suspicious_latin:am

    # game/script.rpy:29 [Sylvie]
    old "Don't worry, the captain sounds rough but he is polite when it matters."
    new "<ar>Don't worry, the captain sounds rough but he is polite when it matters.</ar>"  # QA: no_arabic_script:<ar>Don't worry, the captain sounds rough but he is polite when it matters.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Don't; suspicious_latin:captain; suspicious_latin:sounds; suspicious_latin:the; suspicious_latin:worry

    # game/script.rpy:33 [Professor Hale]
    old "I am Professor Hale. I run the technical interview. Forty-two candidates failed it since 1998."
    new "<ar>I am Professor Hale. I run the technical interview. Forty-two candidates failed it since 1998.</ar>"  # QA: no_arabic_script:<ar>I am Professor Hale. I run the technical interview. Forty-two candidates fai; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Hale; suspicious_latin:Professor; suspicious_latin:am; suspicious_latin:run; suspicious_latin:the

    # game/script.rpy:37
    old "The corridor splits three ways. Where do you go?"
    new "<ar>The corridor splits three ways. Where do you go?</ar>"  # QA: no_arabic_script:<ar>The corridor splits three ways. Where do you go?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:corridor; suspicious_latin:splits; suspicious_latin:three; suspicious_latin:ways

    # game/script.rpy:39
    old "Ask about the station."
    new "<ar>Ask about the station.</ar>"  # QA: no_arabic_script:<ar>Ask about the station.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:about; suspicious_latin:station; suspicious_latin:the

    # game/script.rpy:42
    old "Ask about the professor."
    new "<ar>Ask about the professor.</ar>"  # QA: no_arabic_script:<ar>Ask about the professor.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:about; suspicious_latin:professor; suspicious_latin:the

    # game/script.rpy:46
    old "Leave quietly."
    new "<ar>Leave quietly.</ar>"  # QA: no_arabic_script:<ar>Leave quietly.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Leave; suspicious_latin:quietly

    # game/script.rpy:50 [Sylvie]
    old "The control room is behind the blue door. Mind the cables on the floor."
    new "<ar>The control room is behind the blue door. Mind the cables on the floor.</ar>"  # QA: no_arabic_script:<ar>The control room is behind the blue door. Mind the cables on the floor.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:behind; suspicious_latin:control; suspicious_latin:is; suspicious_latin:room

    # game/script.rpy:54 [Mira]
    old "The control room runs on an old API. It crashes if FPS drops below 30."
    new "<ar>The control room runs on an old API. It crashes if FPS drops below 30.</ar>"  # QA: no_arabic_script:<ar>The control room runs on an old API. It crashes if FPS drops below 30.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:control; suspicious_latin:on; suspicious_latin:room; suspicious_latin:runs

    # game/script.rpy:58 [Captain Rowan]
    old "Station protocol, rule one: never touch the red lever. Ever."
    new "<ar>Station protocol, rule one: never touch the red lever. Ever.</ar>"  # QA: no_arabic_script:<ar>Station protocol, rule one: never touch the red lever. Ever.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Station; suspicious_latin:never; suspicious_latin:one; suspicious_latin:protocol; suspicious_latin:rule

    # game/script.rpy:62 [Sylvie]
    old "Rule two: the night shift always shares its snacks. I brought cookies."
    new "<ar>Rule two: the night shift always shares its snacks. I brought cookies.</ar>"  # QA: no_arabic_script:<ar>Rule two: the night shift always shares its snacks. I brought cookies.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Rule; suspicious_latin:night; suspicious_latin:shift; suspicious_latin:the; suspicious_latin:two

    # game/script.rpy:66
    old "Sylvie offers you a cookie. Take it?"
    new "<ar>Sylvie offers you a cookie. Take it?</ar>"  # QA: no_arabic_script:<ar>Sylvie offers you a cookie. Take it?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Sylvie; suspicious_latin:Take; suspicious_latin:cookie; suspicious_latin:offers; suspicious_latin:you

    # game/script.rpy:68
    old "Take the cookie."
    new "<ar>Take the cookie.</ar>"  # QA: no_arabic_script:<ar>Take the cookie.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Take; suspicious_latin:cookie; suspicious_latin:the

    # game/script.rpy:72
    old "Politely decline."
    new "<ar>Politely decline.</ar>"  # QA: no_arabic_script:<ar>Politely decline.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Politely; suspicious_latin:decline

    # game/script.rpy:76 [Sylvie]
    old "Good choice! Sugar helps with the technical questions, {player_name}."
    new "<ar>Good choice! Sugar helps with the technical questions, {player_name}.</ar>"  # QA: no_arabic_script:<ar>Good choice! Sugar helps with the technical questions, {player_name}.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Good; suspicious_latin:Sugar; suspicious_latin:choice; suspicious_latin:helps; suspicious_latin:with

    # game/script.rpy:80 [Mira]
    old "Wow. Declining free cookies. Bold interview strategy."
    new "<ar>Wow. Declining free cookies. Bold interview strategy.</ar>"  # QA: no_arabic_script:<ar>Wow. Declining free cookies. Bold interview strategy.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Bold; suspicious_latin:Declining; suspicious_latin:Wow; suspicious_latin:cookies; suspicious_latin:free

    # game/script.rpy:84 [Professor Hale]
    old "You wish to know about me? I published 3.14 papers per year. Approximately."
    new "<ar>You wish to know about me? I published 3.14 papers per year. Approximately.</ar>"  # QA: no_arabic_script:<ar>You wish to know about me? I published 3.14 papers per year. Approximately.<; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:You; suspicious_latin:about; suspicious_latin:know; suspicious_latin:to; suspicious_latin:wish

    # game/script.rpy:88 [Professor Hale]
    old "My field is station protocol engineering. The emergency channel is my design."
    new "<ar>My field is station protocol engineering. The emergency channel is my design.</ar>"  # QA: no_arabic_script:<ar>My field is station protocol engineering. The emergency channel is my design; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:My; suspicious_latin:field; suspicious_latin:is; suspicious_latin:protocol; suspicious_latin:station

    # game/script.rpy:92 [Mira]
    old "Translation: he wrote the manual nobody reads. It is 100% footnotes."
    new "<ar>Translation: he wrote the manual nobody reads. It is 100% footnotes.</ar>"  # QA: no_arabic_script:<ar>Translation: he wrote the manual nobody reads. It is 100% footnotes.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Translation; suspicious_latin:he; suspicious_latin:manual; suspicious_latin:the; suspicious_latin:wrote

    # game/script.rpy:96 [Professor Hale]
    old "The archive key opens every door here. Lose it, and you owe me seven favors."
    new "<ar>The archive key opens every door here. Lose it, and you owe me seven favors.</ar>"  # QA: no_arabic_script:<ar>The archive key opens every door here. Lose it, and you owe me seven favors.; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:archive; suspicious_latin:every; suspicious_latin:key; suspicious_latin:opens

    # game/script.rpy:100
    old "The professor watches you. How do you respond?"
    new "<ar>The professor watches you. How do you respond?</ar>"  # QA: no_arabic_script:<ar>The professor watches you. How do you respond?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:How; suspicious_latin:The; suspicious_latin:professor; suspicious_latin:watches; suspicious_latin:you

    # game/script.rpy:102
    old "I am ready."
    new "<ar>I am ready.</ar>"  # QA: no_arabic_script:<ar>I am ready.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:am; suspicious_latin:ready

    # game/script.rpy:106
    old "I am not ready."
    new "<ar>I am not ready.</ar>"  # QA: no_arabic_script:<ar>I am not ready.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:am; suspicious_latin:not; suspicious_latin:ready

    # game/script.rpy:110 [Professor Hale]
    old "Confidence. Good. The night shift needs people who say: I am ready."
    new "<ar>Confidence. Good. The night shift needs people who say: I am ready.</ar>"  # QA: no_arabic_script:<ar>Confidence. Good. The night shift needs people who say: I am ready.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Confidence; suspicious_latin:Good; suspicious_latin:The; suspicious_latin:night; suspicious_latin:shift

    # game/script.rpy:114 [Sylvie]
    old "Hey, it is fine. I said the same thing on my first night shift."
    new "<ar>Hey, it is fine. I said the same thing on my first night shift.</ar>"  # QA: no_arabic_script:<ar>Hey, it is fine. I said the same thing on my first night shift.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Hey; suspicious_latin:fine; suspicious_latin:is; suspicious_latin:it; suspicious_latin:said

    # game/script.rpy:118 [Captain Rowan]
    old "Leaving already? The exit is locked until the interview ends, {player_name}."
    new "<ar>Leaving already? The exit is locked until the interview ends, {player_name}.</ar>"  # QA: no_arabic_script:<ar>Leaving already? The exit is locked until the interview ends, {player_name}.; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Leaving; suspicious_latin:The; suspicious_latin:already; suspicious_latin:exit; suspicious_latin:is

    # game/script.rpy:122 [Mira]
    old "Classic. The door only opens for people with the archive key."
    new "<ar>Classic. The door only opens for people with the archive key.</ar>"  # QA: no_arabic_script:<ar>Classic. The door only opens for people with the archive key.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Classic; suspicious_latin:The; suspicious_latin:door; suspicious_latin:only; suspicious_latin:opens

    # game/script.rpy:126 [Captain Rowan]
    old "Come back inside. That was not a request. That was station protocol."
    new "<ar>Come back inside. That was not a request. That was station protocol.</ar>"  # QA: no_arabic_script:<ar>Come back inside. That was not a request. That was station protocol.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Come; suspicious_latin:That; suspicious_latin:back; suspicious_latin:inside; suspicious_latin:was

    # game/script.rpy:130 [Sylvie]
    old "Sylvie is tired, but she smiles anyway. Follow me back, okay?"
    new "<ar>Sylvie is tired, but she smiles anyway. Follow me back, okay?</ar>"  # QA: no_arabic_script:<ar>Sylvie is tired, but she smiles anyway. Follow me back, okay?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Sylvie; suspicious_latin:but; suspicious_latin:is; suspicious_latin:she; suspicious_latin:tired

    # game/script.rpy:134 [Mira]
    old "So. This whole night feels like a visual novel. Choices and everything."
    new "<ar>So. This whole night feels like a visual novel. Choices and everything.</ar>"  # QA: no_arabic_script:<ar>So. This whole night feels like a visual novel. Choices and everything.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:So; suspicious_latin:This; suspicious_latin:feels; suspicious_latin:night; suspicious_latin:whole

    # game/script.rpy:138 [Sylvie]
    old "Sylvie said she was ready hours ago. She is still waiting, poor thing."
    new "<ar>Sylvie said she was ready hours ago. She is still waiting, poor thing.</ar>"  # QA: no_arabic_script:<ar>Sylvie said she was ready hours ago. She is still waiting, poor thing.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Sylvie; suspicious_latin:ready; suspicious_latin:said; suspicious_latin:she; suspicious_latin:was

    # game/script.rpy:142
    old "The hall clock shows midnight. What now?"
    new "<ar>The hall clock shows midnight. What now?</ar>"  # QA: no_arabic_script:<ar>The hall clock shows midnight. What now?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:clock; suspicious_latin:hall; suspicious_latin:midnight; suspicious_latin:shows

    # game/script.rpy:144
    old "Ask about the archive key."
    new "<ar>Ask about the archive key.</ar>"  # QA: no_arabic_script:<ar>Ask about the archive key.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:about; suspicious_latin:archive; suspicious_latin:key; suspicious_latin:the

    # game/script.rpy:148
    old "Check the mission board."
    new "<ar>Check the mission board.</ar>"  # QA: no_arabic_script:<ar>Check the mission board.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Check; suspicious_latin:board; suspicious_latin:mission; suspicious_latin:the

    # game/script.rpy:152 [Captain Rowan]
    old "The board says: night shift briefing at 00:07 sharp. Do not be late."
    new "<ar>The board says: night shift briefing at 00:07 sharp. Do not be late.</ar>"  # QA: no_arabic_script:<ar>The board says: night shift briefing at 00:07 sharp. Do not be late.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:board; suspicious_latin:night; suspicious_latin:says; suspicious_latin:shift

    # game/script.rpy:156 [Mira]
    old "It also says the coffee machine achieved self-awareness in 1998. Avoid it."
    new "<ar>It also says the coffee machine achieved self-awareness in 1998. Avoid it.</ar>"  # QA: no_arabic_script:<ar>It also says the coffee machine achieved self-awareness in 1998. Avoid it.</; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:It; suspicious_latin:also; suspicious_latin:coffee; suspicious_latin:says; suspicious_latin:the

    # game/script.rpy:160 [Professor Hale]
    old "The archive key rests in locker number 7. The JSON manifest lists 42 items."
    new "<ar>The archive key rests in locker number 7. The JSON manifest lists 42 items.</ar>"  # QA: no_arabic_script:<ar>The archive key rests in locker number 7. The JSON manifest lists 42 items.<; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:archive; suspicious_latin:in; suspicious_latin:key; suspicious_latin:rests

    # game/script.rpy:164 [Sylvie]
    old "I counted the lockers twice. There are {count} lockers on this floor!"
    new "<ar>I counted the lockers twice. There are {count} lockers on this floor!</ar>"  # QA: no_arabic_script:<ar>I counted the lockers twice. There are {count} lockers on this floor!</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:There; suspicious_latin:counted; suspicious_latin:lockers; suspicious_latin:the; suspicious_latin:twice

    # game/script.rpy:168 [Mira]
    old "Your current score is [score], by the way. The station tracks everything."
    new "<ar>Your current score is [score], by the way. The station tracks everything.</ar>"  # QA: no_arabic_script:<ar>Your current score is [score], by the way. The station tracks everything.</a; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Your; suspicious_latin:by; suspicious_latin:current; suspicious_latin:is; suspicious_latin:score

    # game/script.rpy:172
    old "Locker 7 is locked with an old HTTP panel. Try what?"
    new "<ar>Locker 7 is locked with an old HTTP panel. Try what?</ar>"  # QA: no_arabic_script:<ar>Locker 7 is locked with an old HTTP panel. Try what?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Locker; suspicious_latin:an; suspicious_latin:is; suspicious_latin:locked; suspicious_latin:with

    # game/script.rpy:174
    old "Enter 0000."
    new "<ar>Enter 0000.</ar>"  # QA: no_arabic_script:<ar>Enter 0000.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Enter

    # game/script.rpy:177
    old "Ask Mira for help."
    new "<ar>Ask Mira for help.</ar>"  # QA: no_arabic_script:<ar>Ask Mira for help.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:Mira; suspicious_latin:for; suspicious_latin:help

    # game/script.rpy:182 [Mira]
    old "Zero zero zero zero? Really? Even the night shift deserves better hackers."
    new "<ar>Zero zero zero zero? Really? Even the night shift deserves better hackers.</ar>"  # QA: no_arabic_script:<ar>Zero zero zero zero? Really? Even the night shift deserves better hackers.</; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Really; suspicious_latin:Zero; suspicious_latin:zero

    # game/script.rpy:186 [Mira]
    old "Fine. Mira sounded annoyed, but she typed something incredibly fast."
    new "<ar>Fine. Mira sounded annoyed, but she typed something incredibly fast.</ar>"  # QA: no_arabic_script:<ar>Fine. Mira sounded annoyed, but she typed something incredibly fast.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Fine; suspicious_latin:Mira; suspicious_latin:annoyed; suspicious_latin:but; suspicious_latin:sounded

    # game/script.rpy:190 [Captain Rowan]
    old "The locker clicks open. Take the archive key, {player_name}."
    new "<ar>The locker clicks open. Take the archive key, {player_name}.</ar>"  # QA: no_arabic_script:<ar>The locker clicks open. Take the archive key, {player_name}.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Take; suspicious_latin:The; suspicious_latin:clicks; suspicious_latin:locker; suspicious_latin:open

    # game/script.rpy:194
    old "The archive key glows faintly. What do you do?"
    new "<ar>The archive key glows faintly. What do you do?</ar>"  # QA: no_arabic_script:<ar>The archive key glows faintly. What do you do?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:archive; suspicious_latin:faintly; suspicious_latin:glows; suspicious_latin:key

    # game/script.rpy:196
    old "Take it carefully."
    new "<ar>Take it carefully.</ar>"  # QA: no_arabic_script:<ar>Take it carefully.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Take; suspicious_latin:carefully; suspicious_latin:it

    # game/script.rpy:200
    old "Ask what it opens first."
    new "<ar>Ask what it opens first.</ar>"  # QA: no_arabic_script:<ar>Ask what it opens first.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:first; suspicious_latin:it; suspicious_latin:opens; suspicious_latin:what

    # game/script.rpy:204 [Professor Hale]
    old "Excellent. The archive key responds to polite holders only."
    new "<ar>Excellent. The archive key responds to polite holders only.</ar>"  # QA: no_arabic_script:<ar>Excellent. The archive key responds to polite holders only.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Excellent; suspicious_latin:The; suspicious_latin:archive; suspicious_latin:key; suspicious_latin:responds

    # game/script.rpy:208 [Professor Hale]
    old "It opens the emergency channel room. Professor Hale thanked her assistant."
    new "<ar>It opens the emergency channel room. Professor Hale thanked her assistant.</ar>"  # QA: no_arabic_script:<ar>It opens the emergency channel room. Professor Hale thanked her assistant.</; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:It; suspicious_latin:channel; suspicious_latin:emergency; suspicious_latin:opens; suspicious_latin:the

    # game/script.rpy:212 [Sylvie]
    old "Are you sure about all this? You look nervous, {player_name}."
    new "<ar>Are you sure about all this? You look nervous, {player_name}.</ar>"  # QA: no_arabic_script:<ar>Are you sure about all this? You look nervous, {player_name}.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Are; suspicious_latin:about; suspicious_latin:all; suspicious_latin:sure; suspicious_latin:you

    # game/script.rpy:216 [Captain Rowan]
    old "You are late for your own interview. Impressive record."
    new "<ar>You are late for your own interview. Impressive record.</ar>"  # QA: no_arabic_script:<ar>You are late for your own interview. Impressive record.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:You; suspicious_latin:are; suspicious_latin:for; suspicious_latin:late; suspicious_latin:your

    # game/script.rpy:220 [Mira]
    old "I knew you would come back. Nobody leaves Station 7 on the first try."
    new "<ar>I knew you would come back. Nobody leaves Station 7 on the first try.</ar>"  # QA: no_arabic_script:<ar>I knew you would come back. Nobody leaves Station 7 on the first try.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:back; suspicious_latin:come; suspicious_latin:knew; suspicious_latin:would; suspicious_latin:you

    # game/script.rpy:224 [Sylvie]
    old "Sylvie is tired. Carrying the night shift snacks is heavy work, you know?"
    new "<ar>Sylvie is tired. Carrying the night shift snacks is heavy work, you know?</ar>"  # QA: no_arabic_script:<ar>Sylvie is tired. Carrying the night shift snacks is heavy work, you know?</a; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Carrying; suspicious_latin:Sylvie; suspicious_latin:is; suspicious_latin:the; suspicious_latin:tired

    # game/script.rpy:228 [Captain Rowan]
    old "Captain Rowan told him to wait outside. Him, not you. Keep walking."
    new "<ar>Captain Rowan told him to wait outside. Him, not you. Keep walking.</ar>"  # QA: no_arabic_script:<ar>Captain Rowan told him to wait outside. Him, not you. Keep walking.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Captain; suspicious_latin:Rowan; suspicious_latin:him; suspicious_latin:to; suspicious_latin:told

    # game/script.rpy:232 [Professor Hale]
    old "Emotions are data. Tiredness means the night shift is working as designed."
    new "<ar>Emotions are data. Tiredness means the night shift is working as designed.</ar>"  # QA: no_arabic_script:<ar>Emotions are data. Tiredness means the night shift is working as designed.</; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Emotions; suspicious_latin:Tiredness; suspicious_latin:are; suspicious_latin:data; suspicious_latin:means

    # game/script.rpy:236 [Mira]
    old "Okay, serious question from the OpenAI fan club: is Qwen3 better at interviews?"
    new "<ar>Okay, serious question from the OpenAI fan club: is Qwen3 better at interviews?</ar>"  # QA: no_arabic_script:<ar>Okay, serious question from the OpenAI fan club: is Qwen3 better at intervie; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Okay; suspicious_latin:from; suspicious_latin:question; suspicious_latin:serious; suspicious_latin:the

    # game/script.rpy:240 [Sylvie]
    old "Do not listen to her. The manual is at https://example.com/station/alpha"
    new "<ar>Do not listen to her. The manual is at https://example.com/station/alpha</ar>"  # QA: no_arabic_script:<ar>Do not listen to her. The manual is at https://example.com/station/alpha</ar; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Do; suspicious_latin:her; suspicious_latin:listen; suspicious_latin:not; suspicious_latin:to

    # game/script.rpy:244 [Captain Rowan]
    old "Enough chatter. The emergency channel just lit up. Move, all of you!"
    new "<ar>Enough chatter. The emergency channel just lit up. Move, all of you!</ar>"  # QA: no_arabic_script:<ar>Enough chatter. The emergency channel just lit up. Move, all of you!</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Enough; suspicious_latin:The; suspicious_latin:channel; suspicious_latin:chatter; suspicious_latin:emergency

    # game/script.rpy:248 [Mira]
    old "<b>Emergency!</b> I repeat: this is not a drill, people!"
    new "<ar><b>Emergency!</b> I repeat: this is not a drill, people!</ar>"  # QA: no_arabic_script:<ar><b>Emergency!</b> I repeat: this is not a drill, people!</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Emergency; suspicious_latin:is; suspicious_latin:not; suspicious_latin:repeat; suspicious_latin:this

    # game/script.rpy:252 [Professor Hale]
    old "The control room smells of ozone and old decisions. Forty-two lights blink red, then green, then red again, while the ancient ventilation system hums a low song that nobody remembers voting for, and I must admit the whole room feels like it is holding its breath waiting for someone competent to arrive."
    new "<ar>The control room smells of ozone and old decisions. Forty-two lights blink red, then green, then red again, while the ancient ventilation system hums a low song that nobody remembers voting for, and I must admit the whole room feels like it is holding its breath waiting for someone competent to arrive.</ar>"  # QA: no_arabic_script:<ar>The control room smells of ozone and old decisions. Forty-two lights blink r; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:control; suspicious_latin:of; suspicious_latin:room; suspicious_latin:smells

    # game/script.rpy:256
    old "Alarms everywhere. Your call?"
    new "<ar>Alarms everywhere. Your call?</ar>"  # QA: no_arabic_script:<ar>Alarms everywhere. Your call?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Alarms; suspicious_latin:Your; suspicious_latin:call; suspicious_latin:everywhere

    # game/script.rpy:258
    old "Follow station protocol."
    new "<ar>Follow station protocol.</ar>"  # QA: no_arabic_script:<ar>Follow station protocol.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Follow; suspicious_latin:protocol; suspicious_latin:station

    # game/script.rpy:262
    old "Improvise wildly."
    new "<ar>Improvise wildly.</ar>"  # QA: no_arabic_script:<ar>Improvise wildly.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Improvise; suspicious_latin:wildly

    # game/script.rpy:266 [Captain Rowan]
    old "Good. Station protocol, page one: protect the archive key with your life."
    new "<ar>Good. Station protocol, page one: protect the archive key with your life.</ar>"  # QA: no_arabic_script:<ar>Good. Station protocol, page one: protect the archive key with your life.</a; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Good; suspicious_latin:Station; suspicious_latin:one; suspicious_latin:page; suspicious_latin:protocol

    # game/script.rpy:270 [Sylvie]
    old "Page two: hold my hand? No wait, that is just Sylvie being Sylvie. Sorry!"
    new "<ar>Page two: hold my hand? No wait, that is just Sylvie being Sylvie. Sorry!</ar>"  # QA: no_arabic_script:<ar>Page two: hold my hand? No wait, that is just Sylvie being Sylvie. Sorry!</a; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Page; suspicious_latin:hand; suspicious_latin:hold; suspicious_latin:my; suspicious_latin:two

    # game/script.rpy:274
    old "The alarm pattern changes. Respond?"
    new "<ar>The alarm pattern changes. Respond?</ar>"  # QA: no_arabic_script:<ar>The alarm pattern changes. Respond?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Respond; suspicious_latin:The; suspicious_latin:alarm; suspicious_latin:changes; suspicious_latin:pattern

    # game/script.rpy:276
    old "Open the emergency channel."
    new "<ar>Open the emergency channel.</ar>"  # QA: no_arabic_script:<ar>Open the emergency channel.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Open; suspicious_latin:channel; suspicious_latin:emergency; suspicious_latin:the

    # game/script.rpy:280
    old "Ask Mira what it means."
    new "<ar>Ask Mira what it means.</ar>"  # QA: no_arabic_script:<ar>Ask Mira what it means.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:Mira; suspicious_latin:it; suspicious_latin:means; suspicious_latin:what

    # game/script.rpy:284 [Mira]
    old "Wild improvisation! My favorite protocol. The night shift salutes you."
    new "<ar>Wild improvisation! My favorite protocol. The night shift salutes you.</ar>"  # QA: no_arabic_script:<ar>Wild improvisation! My favorite protocol. The night shift salutes you.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:My; suspicious_latin:Wild; suspicious_latin:favorite; suspicious_latin:improvisation; suspicious_latin:protocol

    # game/script.rpy:288 [Mira]
    old "It means the coffee machine woke up again. Or the station is doomed. Fifty-fifty."
    new "<ar>It means the coffee machine woke up again. Or the station is doomed. Fifty-fifty.</ar>"  # QA: no_arabic_script:<ar>It means the coffee machine woke up again. Or the station is doomed. Fifty-f; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:It; suspicious_latin:coffee; suspicious_latin:machine; suspicious_latin:means; suspicious_latin:the

    # game/script.rpy:292
    old "Decide fast: the lights are failing."
    new "<ar>Decide fast: the lights are failing.</ar>"  # QA: no_arabic_script:<ar>Decide fast: the lights are failing.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Decide; suspicious_latin:are; suspicious_latin:fast; suspicious_latin:lights; suspicious_latin:the

    # game/script.rpy:294
    old "Grab the archive key and run."
    new "<ar>Grab the archive key and run.</ar>"  # QA: no_arabic_script:<ar>Grab the archive key and run.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Grab; suspicious_latin:and; suspicious_latin:archive; suspicious_latin:key; suspicious_latin:the

    # game/script.rpy:297
    old "Stay and fix the panel."
    new "<ar>Stay and fix the panel.</ar>"  # QA: no_arabic_script:<ar>Stay and fix the panel.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Stay; suspicious_latin:and; suspicious_latin:fix; suspicious_latin:panel; suspicious_latin:the

    # game/script.rpy:302 [Professor Hale]
    old "The emergency channel crackles. A voice older than Station 7 itself whispers seven numbers, then silence, then static, then a single polite cough that somehow contains more menace than the entire alarm system combined."
    new "<ar>The emergency channel crackles. A voice older than Station 7 itself whispers seven numbers, then silence, then static, then a single polite cough that somehow contains more menace than the entire alarm system combined.</ar>"  # QA: no_arabic_script:<ar>The emergency channel crackles. A voice older than Station 7 itself whispers; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:channel; suspicious_latin:crackles; suspicious_latin:emergency; suspicious_latin:voice

    # game/script.rpy:306 [Sylvie]
    old "Did... did it just cough at us? Sylvie hides behind {player_name}."
    new "<ar>Did... did it just cough at us? Sylvie hides behind {player_name}.</ar>"  # QA: no_arabic_script:<ar>Did... did it just cough at us? Sylvie hides behind {player_name}.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Did; suspicious_latin:cough; suspicious_latin:did; suspicious_latin:it; suspicious_latin:just

    # game/script.rpy:310 [Captain Rowan]
    old "Steady. The night shift has survived worse. Probably. Maybe."
    new "<ar>Steady. The night shift has survived worse. Probably. Maybe.</ar>"  # QA: no_arabic_script:<ar>Steady. The night shift has survived worse. Probably. Maybe.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Steady; suspicious_latin:The; suspicious_latin:has; suspicious_latin:night; suspicious_latin:shift

    # game/script.rpy:314 [Mira]
    old "Plot twist: it was the coffee machine all along. Told you. Night shift legend status: pending."
    new "<ar>Plot twist: it was the coffee machine all along. Told you. Night shift legend status: pending.</ar>"  # QA: no_arabic_script:<ar>Plot twist: it was the coffee machine all along. Told you. Night shift legen; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Plot; suspicious_latin:it; suspicious_latin:the; suspicious_latin:twist; suspicious_latin:was

    # game/script.rpy:318 [Professor Hale]
    old "You fixed the panel with 100% confidence and 0% understanding. Hired."
    new "<ar>You fixed the panel with 100% confidence and 0% understanding. Hired.</ar>"  # QA: no_arabic_script:<ar>You fixed the panel with 100% confidence and 0% understanding. Hired.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:You; suspicious_latin:fixed; suspicious_latin:panel; suspicious_latin:the; suspicious_latin:with

    # game/script.rpy:322
    old "Dawn approaches. How do you end the night?"
    new "<ar>Dawn approaches. How do you end the night?</ar>"  # QA: no_arabic_script:<ar>Dawn approaches. How do you end the night?</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Dawn; suspicious_latin:How; suspicious_latin:approaches; suspicious_latin:do; suspicious_latin:you

    # game/script.rpy:324
    old "Accept the night shift job."
    new "<ar>Accept the night shift job.</ar>"  # QA: no_arabic_script:<ar>Accept the night shift job.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Accept; suspicious_latin:job; suspicious_latin:night; suspicious_latin:shift; suspicious_latin:the

    # game/script.rpy:328
    old "Ask for one more test."
    new "<ar>Ask for one more test.</ar>"  # QA: no_arabic_script:<ar>Ask for one more test.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Ask; suspicious_latin:for; suspicious_latin:more; suspicious_latin:one; suspicious_latin:test

    # game/script.rpy:332 [Captain Rowan]
    old "Welcome to Station 7, {player_name}. The night shift is yours."
    new "<ar>Welcome to Station 7, {player_name}. The night shift is yours.</ar>"  # QA: no_arabic_script:<ar>Welcome to Station 7, {player_name}. The night shift is yours.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Station; suspicious_latin:The; suspicious_latin:Welcome; suspicious_latin:night; suspicious_latin:to

    # game/script.rpy:336 [Sylvie]
    old "We did it! Cookies for everyone! Score: [score] points!"
    new "<ar>We did it! Cookies for everyone! Score: [score] points!</ar>"  # QA: no_arabic_script:<ar>We did it! Cookies for everyone! Score: [score] points!</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Cookies; suspicious_latin:We; suspicious_latin:did; suspicious_latin:for; suspicious_latin:it

    # game/script.rpy:340
    old "One last formality..."
    new "<ar>One last formality...</ar>"  # QA: no_arabic_script:<ar>One last formality...</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:One; suspicious_latin:formality; suspicious_latin:last

    # game/script.rpy:342
    old "Sign the contract."
    new "<ar>Sign the contract.</ar>"  # QA: no_arabic_script:<ar>Sign the contract.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Sign; suspicious_latin:contract; suspicious_latin:the

    # game/script.rpy:346
    old "Read it first (1998 clauses)."
    new "<ar>Read it first (1998 clauses).</ar>"  # QA: no_arabic_script:<ar>Read it first (1998 clauses).</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Read; suspicious_latin:clauses; suspicious_latin:first; suspicious_latin:it

    # game/script.rpy:350 [Mira]
    old "One more test? The interview never ends here. That is the station protocol."
    new "<ar>One more test? The interview never ends here. That is the station protocol.</ar>"  # QA: no_arabic_script:<ar>One more test? The interview never ends here. That is the station protocol.<; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:One; suspicious_latin:The; suspicious_latin:interview; suspicious_latin:more; suspicious_latin:test

    # game/script.rpy:354 [Professor Hale]
    old "Clause 3.14: the signee agrees to love paperwork. Sign here: ______"
    new "<ar>Clause 3.14: the signee agrees to love paperwork. Sign here: ______</ar>"  # QA: no_arabic_script:<ar>Clause 3.14: the signee agrees to love paperwork. Sign here: ______</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Clause; suspicious_latin:agrees; suspicious_latin:signee; suspicious_latin:the; suspicious_latin:to

    # game/script.rpy:358
    old "The pen hovers over the paper."
    new "<ar>The pen hovers over the paper.</ar>"  # QA: no_arabic_script:<ar>The pen hovers over the paper.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:The; suspicious_latin:hovers; suspicious_latin:over; suspicious_latin:pen; suspicious_latin:the

    # game/script.rpy:360
    old "Sign it."
    new "<ar>Sign it.</ar>"  # QA: no_arabic_script:<ar>Sign it.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Sign; suspicious_latin:it

    # game/script.rpy:363
    old "Run for the exit!"
    new "<ar>Run for the exit!</ar>"  # QA: no_arabic_script:<ar>Run for the exit!</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Run; suspicious_latin:exit; suspicious_latin:for; suspicious_latin:the

    # game/script.rpy:367 [Sylvie]
    old "Hired! Legend of the night shift! See you at 00:07, {player_name}!"
    new "<ar>Hired! Legend of the night shift! See you at 00:07, {player_name}!</ar>"  # QA: no_arabic_script:<ar>Hired! Legend of the night shift! See you at 00:07, {player_name}!</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Hired; suspicious_latin:Legend; suspicious_latin:night; suspicious_latin:of; suspicious_latin:the

    # game/script.rpy:371 [Mira]
    old "Escorted out by Captain Rowan himself. Honestly? Worth it. 7/10 night."
    new "<ar>Escorted out by Captain Rowan himself. Honestly? Worth it. 7/10 night.</ar>"  # QA: no_arabic_script:<ar>Escorted out by Captain Rowan himself. Honestly? Worth it. 7/10 night.</ar>; placeholder_extra:</ar>; placeholder_extra:<ar>; suspicious_latin:Captain; suspicious_latin:Escorted; suspicious_latin:Rowan; suspicious_latin:by; suspicious_latin:out
