# GENERATED by tools/json_to_rpy.py - do not hand-edit.
# Source of truth: game_data/dialogue.json

define c0 = Character("Sylvie")
define c1 = Character("Mira")
define c2 = Character("Captain Rowan")
define c3 = Character("Professor Hale")

label start:
    jump node_dlg_001

label node_dlg_001:
    c0 "Good evening. I thought you were going to be late."
    jump node_dlg_002

label node_dlg_002:
    c0 "Welcome to Station 7, {player_name}! Night shift starts in seven minutes."
    jump node_dlg_003

label node_dlg_003:
    c1 "Great. Another interview at midnight. This station protocol makes no sense."
    jump node_dlg_004

label node_dlg_004:
    c2 "Quiet, Mira. {player_name}, I am Captain Rowan. Walk with me to the control room."
    jump node_dlg_005

label node_dlg_005:
    c0 "Don't worry, the captain sounds rough but he is polite when it matters."
    jump node_dlg_006

label node_dlg_006:
    c3 "I am Professor Hale. I run the technical interview. Forty-two candidates failed it since 1998."
    jump node_dlg_007

label node_dlg_007:
    "The corridor splits three ways. Where do you go?"
    menu:
        "Ask about the station.":
            jump node_dlg_008
    menu:
        "Ask about the professor.":
            $ flags_curious = True
            jump node_dlg_015
    menu:
        "Leave quietly.":
            jump node_dlg_022

label node_dlg_008:
    c0 "The control room is behind the blue door. Mind the cables on the floor."
    jump node_dlg_009

label node_dlg_009:
    c1 "The control room runs on an old API. It crashes if FPS drops below 30."
    jump node_dlg_010

label node_dlg_010:
    c2 "Station protocol, rule one: never touch the red lever. Ever."
    jump node_dlg_011

label node_dlg_011:
    c0 "Rule two: the night shift always shares its snacks. I brought cookies."
    jump node_dlg_012

label node_dlg_012:
    "Sylvie offers you a cookie. Take it?"
    menu:
        "Take the cookie.":
            $ flags_cookie = True
            jump node_dlg_013
    menu:
        "Politely decline.":
            jump node_dlg_014

label node_dlg_013:
    c0 "Good choice! Sugar helps with the technical questions, {player_name}."
    jump node_dlg_026

label node_dlg_014:
    c1 "Wow. Declining free cookies. Bold interview strategy."
    jump node_dlg_026

label node_dlg_015:
    c3 "You wish to know about me? I published 3.14 papers per year. Approximately."
    jump node_dlg_016

label node_dlg_016:
    c3 "My field is station protocol engineering. The emergency channel is my design."
    jump node_dlg_017

label node_dlg_017:
    c1 "Translation: he wrote the manual nobody reads. It is 100% footnotes."
    jump node_dlg_018

label node_dlg_018:
    c3 "The archive key opens every door here. Lose it, and you owe me seven favors."
    jump node_dlg_019

label node_dlg_019:
    "The professor watches you. How do you respond?"
    menu:
        "I am ready.":
            $ flags_confident = True
            jump node_dlg_020
    menu:
        "I am not ready.":
            jump node_dlg_021

label node_dlg_020:
    c3 "Confidence. Good. The night shift needs people who say: I am ready."
    jump node_dlg_026

label node_dlg_021:
    c0 "Hey, it is fine. I said the same thing on my first night shift."
    jump node_dlg_026

label node_dlg_022:
    c2 "Leaving already? The exit is locked until the interview ends, {player_name}."
    jump node_dlg_023

label node_dlg_023:
    c1 "Classic. The door only opens for people with the archive key."
    jump node_dlg_024

label node_dlg_024:
    c2 "Come back inside. That was not a request. That was station protocol."
    jump node_dlg_025

label node_dlg_025:
    c0 "Sylvie is tired, but she smiles anyway. Follow me back, okay?"
    jump node_dlg_026

label node_dlg_026:
    c1 "So. This whole night feels like a visual novel. Choices and everything."
    jump node_dlg_027

label node_dlg_027:
    c0 "Sylvie said she was ready hours ago. She is still waiting, poor thing."
    jump node_dlg_028

label node_dlg_028:
    "The hall clock shows midnight. What now?"
    menu:
        "Ask about the archive key.":
            $ flags_asked_key = True
            jump node_dlg_031
    menu:
        "Check the mission board.":
            jump node_dlg_029

label node_dlg_029:
    c2 "The board says: night shift briefing at 00:07 sharp. Do not be late."
    jump node_dlg_030

label node_dlg_030:
    c1 "It also says the coffee machine achieved self-awareness in 1998. Avoid it."
    jump node_dlg_031

label node_dlg_031:
    c3 "The archive key rests in locker number 7. The JSON manifest lists 42 items."
    jump node_dlg_032

label node_dlg_032:
    c0 "I counted the lockers twice. There are {count} lockers on this floor!"
    jump node_dlg_033

label node_dlg_033:
    c1 "Your current score is [score], by the way. The station tracks everything."
    jump node_dlg_034

label node_dlg_034:
    "Locker 7 is locked with an old HTTP panel. Try what?"
    menu:
        "Enter 0000.":
            jump node_dlg_035
    menu:
        "Ask Mira for help.":
            $ flags_mira_helps = True
            jump node_dlg_036

label node_dlg_035:
    c1 "Zero zero zero zero? Really? Even the night shift deserves better hackers."
    jump node_dlg_037

label node_dlg_036:
    c1 "Fine. Mira sounded annoyed, but she typed something incredibly fast."
    jump node_dlg_037

label node_dlg_037:
    c2 "The locker clicks open. Take the archive key, {player_name}."
    jump node_dlg_038

label node_dlg_038:
    "The archive key glows faintly. What do you do?"
    menu:
        "Take it carefully.":
            $ flags_has_key = True
            jump node_dlg_039
    menu:
        "Ask what it opens first.":
            jump node_dlg_040

label node_dlg_039:
    c3 "Excellent. The archive key responds to polite holders only."
    jump node_dlg_041

label node_dlg_040:
    c3 "It opens the emergency channel room. Professor Hale thanked her assistant."
    jump node_dlg_041

label node_dlg_041:
    c0 "Are you sure about all this? You look nervous, {player_name}."
    jump node_dlg_042

label node_dlg_042:
    c2 "You are late for your own interview. Impressive record."
    jump node_dlg_043

label node_dlg_043:
    c1 "I knew you would come back. Nobody leaves Station 7 on the first try."
    jump node_dlg_044

label node_dlg_044:
    c0 "Sylvie is tired. Carrying the night shift snacks is heavy work, you know?"
    jump node_dlg_045

label node_dlg_045:
    c2 "Captain Rowan told him to wait outside. Him, not you. Keep walking."
    jump node_dlg_046

label node_dlg_046:
    c3 "Emotions are data. Tiredness means the night shift is working as designed."
    jump node_dlg_047

label node_dlg_047:
    c1 "Okay, serious question from the OpenAI fan club: is Qwen3 better at interviews?"
    jump node_dlg_048

label node_dlg_048:
    c0 "Do not listen to her. The manual is at https://example.com/station/alpha"
    jump node_dlg_049

label node_dlg_049:
    c2 "Enough chatter. The emergency channel just lit up. Move, all of you!"
    jump node_dlg_050

label node_dlg_050:
    c1 "<b>Emergency!</b> I repeat: this is not a drill, people!"
    jump node_dlg_051

label node_dlg_051:
    c3 "The control room smells of ozone and old decisions. Forty-two lights blink red, then green, then red again, while the ancient ventilation system hums a low song that nobody remembers voting for, and I must admit the whole room feels like it is holding its breath waiting for someone competent to arrive."
    jump node_dlg_052

label node_dlg_052:
    "Alarms everywhere. Your call?"
    menu:
        "Follow station protocol.":
            $ flags_protocol = True
            jump node_dlg_053
    menu:
        "Improvise wildly.":
            jump node_dlg_056

label node_dlg_053:
    c2 "Good. Station protocol, page one: protect the archive key with your life."
    jump node_dlg_054

label node_dlg_054:
    c0 "Page two: hold my hand? No wait, that is just Sylvie being Sylvie. Sorry!"
    jump node_dlg_055

label node_dlg_055:
    "The alarm pattern changes. Respond?"
    menu:
        "Open the emergency channel.":
            $ flags_channel = True
            jump node_dlg_059
    menu:
        "Ask Mira what it means.":
            jump node_dlg_057

label node_dlg_056:
    c1 "Wild improvisation! My favorite protocol. The night shift salutes you."
    jump node_dlg_057

label node_dlg_057:
    c1 "It means the coffee machine woke up again. Or the station is doomed. Fifty-fifty."
    jump node_dlg_058

label node_dlg_058:
    "Decide fast: the lights are failing."
    menu:
        "Grab the archive key and run.":
            jump node_dlg_059
    menu:
        "Stay and fix the panel.":
            $ flags_hero = True
            jump node_dlg_063

label node_dlg_059:
    c3 "The emergency channel crackles. A voice older than Station 7 itself whispers seven numbers, then silence, then static, then a single polite cough that somehow contains more menace than the entire alarm system combined."
    jump node_dlg_060

label node_dlg_060:
    c0 "Did... did it just cough at us? Sylvie hides behind {player_name}."
    jump node_dlg_061

label node_dlg_061:
    c2 "Steady. The night shift has survived worse. Probably. Maybe."
    jump node_dlg_062

label node_dlg_062:
    c1 "Plot twist: it was the coffee machine all along. Told you. Night shift legend status: pending."
    jump node_dlg_064

label node_dlg_063:
    c3 "You fixed the panel with 100% confidence and 0% understanding. Hired."
    jump node_dlg_064

label node_dlg_064:
    "Dawn approaches. How do you end the night?"
    menu:
        "Accept the night shift job.":
            $ flags_hired = True
            jump node_dlg_065
    menu:
        "Ask for one more test.":
            jump node_dlg_068

label node_dlg_065:
    c2 "Welcome to Station 7, {player_name}. The night shift is yours."
    jump node_dlg_066

label node_dlg_066:
    c0 "We did it! Cookies for everyone! Score: [score] points!"
    jump node_dlg_067

label node_dlg_067:
    "One last formality..."
    menu:
        "Sign the contract.":
            $ flags_signed = True
            jump node_dlg_071
    menu:
        "Read it first (1998 clauses).":
            jump node_dlg_069

label node_dlg_068:
    c1 "One more test? The interview never ends here. That is the station protocol."
    jump node_dlg_069

label node_dlg_069:
    c3 "Clause 3.14: the signee agrees to love paperwork. Sign here: ______"
    jump node_dlg_070

label node_dlg_070:
    "The pen hovers over the paper."
    menu:
        "Sign it.":
            jump node_dlg_071
    menu:
        "Run for the exit!":
            jump node_dlg_072

label node_dlg_071:
    c0 "Hired! Legend of the night shift! See you at 00:07, {player_name}!"
    return

label node_dlg_072:
    c1 "Escorted out by Captain Rowan himself. Honestly? Worth it. 7/10 night."
    return
